"""Fill a magenta region so most of it becomes shirt and only the border (the edge
facing the existing transparent background) becomes transparent background.

Pipeline:
  1. mask = magenta pixels.
  2. border = magenta pixels within `--border` px of the existing transparent area.
  3. core   = magenta minus border  -> inpainted as shirt by Stable Diffusion.
  4. output alpha: core -> opaque (shirt), border -> transparent.
"""

import argparse
from pathlib import Path

import numpy as np
import torch
from PIL import Image


def dilate(mask: np.ndarray, iterations: int) -> np.ndarray:
    m = mask > 0
    for _ in range(iterations):
        out = m.copy()
        out[:-1, :] |= m[1:, :]
        out[1:, :] |= m[:-1, :]
        out[:, :-1] |= m[:, 1:]
        out[:, 1:] |= m[:, :-1]
        m = out
    return m


def erode(mask: np.ndarray, iterations: int) -> np.ndarray:
    return ~dilate(~mask, iterations)


def close(mask: np.ndarray, iterations: int) -> np.ndarray:
    """Morphological closing: fills holes/notches thinner than `iterations`."""
    return erode(dilate(mask, iterations), iterations)


def working_size(w: int, h: int, target: int):
    scale = target / max(w, h)
    return max(8, round(w * scale / 8) * 8), max(8, round(h * scale / 8) * 8)


def main() -> None:
    p = argparse.ArgumentParser(description="Fill magenta with shirt; transparent border.")
    p.add_argument("input", type=Path)
    p.add_argument("-o", "--output", type=Path, required=True)
    p.add_argument("--color", type=int, nargs=3, default=[255, 0, 255])
    p.add_argument("--tolerance", type=int, default=30)
    p.add_argument("--border", type=int, default=12,
                   help="Width in px of the transparent background border")
    p.add_argument("--prompt", default="plain white cotton collared button-up shirt fabric, "
                   "small dark diamond print, natural daylight photo, sharp focus")
    p.add_argument("--negative", default="magenta, pink, purple, green, colorful, rainbow, "
                   "neon, saturated, abstract, distorted, sky, wall, blurry, text, watermark")
    p.add_argument("--steps", type=int, default=30)
    p.add_argument("--guidance", type=float, default=7.0)
    p.add_argument("--size", type=int, default=512)
    p.add_argument("--model", default="stable-diffusion-v1-5/stable-diffusion-inpainting")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--debug-masks", type=Path, help="Optional path to save a mask preview")
    args = p.parse_args()

    img = Image.open(args.input).convert("RGBA")
    W, H = img.size
    arr = np.asarray(img)
    rgb = arr[:, :, :3].astype(np.int16)
    alpha = arr[:, :, 3]

    target = np.array(args.color, dtype=np.int16)
    R, G, B = rgb[:, :, 0], rgb[:, :, 1], rgb[:, :, 2]
    magenta = np.abs(rgb - target).max(axis=2) <= args.tolerance
    # Hue-based magenta/pink: R and B both elevated above G. Catches the light-pink
    # anti-aliased tint bleeding onto the white shirt that a distance match misses.
    pinkish = (R > G + 18) & (B > G + 18) & (R > 140) & (B > 140)
    transparent = alpha < 128
    opaque = ~transparent

    # Solid silhouette of "patch + person", with interior notches/holes from the imperfect
    # cutout filled in by a morphological close. Eroding this solid blob removes only a thin
    # OUTER-contour rim -- so, unlike the old near-bg test, it can never punch interior holes.
    solid = close(opaque | magenta, args.border + 4)
    eroded = erode(solid, args.border)
    rim = solid & ~eroded
    patch_zone = dilate(magenta, args.border + 6)

    transparent_new = rim & patch_zone            # thin outer rim of the patch -> transparent
    fill_zone = solid & ~transparent_new & patch_zone   # everything else in patch -> opaque shirt

    # Pink halo just inside the magenta edge (a bit wider than the magenta itself).
    halo = pinkish & dilate(magenta, 30)
    # Pixels whose RGB must be regenerated: original magenta, pink halo, or interior holes.
    regen = (magenta | halo | transparent) & fill_zone

    print(f"magenta: {int(magenta.sum())} px | fill(shirt): {int(fill_zone.sum())} px "
          f"| transparent rim: {int(transparent_new.sum())} px | regen: {int(regen.sum())} px")

    if args.debug_masks:
        dbg = np.asarray(img.convert("RGB")).copy()
        dbg[fill_zone] = [0, 200, 0]        # green = opaque shirt
        dbg[transparent_new] = [255, 0, 0]  # red   = transparent
        dbg[regen & fill_zone] = [0, 0, 255]  # blue  = SD-regenerated
        Image.fromarray(dbg).save(args.debug_masks)
        print(f"Saved mask preview: {args.debug_masks}")

    # Neutralize magenta/pink/holes to off-white BEFORE SD/compositing so nothing can bleed
    # when SD's low-res output is upscaled; the masked area is regenerated by SD anyway.
    clean = arr[:, :, :3].copy()
    clean[magenta | halo | (transparent & fill_zone)] = [235, 233, 230]
    rgb_img = Image.fromarray(clean, "RGB")

    sd_mask = dilate(regen, 3) & fill_zone
    sd_mask_img = Image.fromarray((sd_mask * 255).astype(np.uint8), "L")

    from diffusers import StableDiffusionInpaintPipeline

    device = "cuda" if torch.cuda.is_available() else "cpu"
    dtype = torch.float16 if device == "cuda" else torch.float32
    print(f"Device: {device} ({dtype}). Loading {args.model} ...")
    pipe = StableDiffusionInpaintPipeline.from_pretrained(args.model, torch_dtype=dtype).to(device)
    pipe.set_progress_bar_config(disable=False)

    ww, wh = working_size(W, H, args.size)
    out = pipe(
        prompt=args.prompt,
        negative_prompt=args.negative,
        image=rgb_img.resize((ww, wh), Image.LANCZOS),
        mask_image=sd_mask_img.resize((ww, wh), Image.NEAREST),
        num_inference_steps=args.steps,
        guidance_scale=args.guidance,
        height=wh, width=ww,
        generator=torch.Generator(device=device).manual_seed(args.seed),
    ).images[0].resize((W, H), Image.LANCZOS)

    # Composite generated shirt only inside the SD mask.
    sd_mask_pil = Image.fromarray((sd_mask * 255).astype(np.uint8), "L")
    result_rgb = Image.composite(out, rgb_img, sd_mask_pil)

    # Alpha: fill zone opaque (no interior holes), thin outer rim transparent.
    out_alpha = alpha.copy()
    out_alpha[fill_zone] = 255
    out_alpha[transparent_new] = 0

    # Safety net: if any magenta/pink survived in the final RGB, neutralize it to off-white
    # (opaque shirt inside the fill zone) so no colored fringe remains.
    res_rgb = np.asarray(result_rgb, dtype=np.int16)
    rR, rG, rB = res_rgb[:, :, 0], res_rgb[:, :, 1], res_rgb[:, :, 2]
    res_pink = (rR > rG + 18) & (rB > rG + 18) & (rR > 140) & (rB > 140)
    leftover = res_pink & (out_alpha > 0)
    if leftover.any():
        res_rgb[leftover] = [235, 233, 230]
        result_rgb = Image.fromarray(res_rgb.astype(np.uint8), "RGB")
    print(f"cleanup: neutralized {int(leftover.sum())} residual pink px")

    result = result_rgb.convert("RGBA")
    result.putalpha(Image.fromarray(out_alpha, "L"))
    result.save(args.output)
    print(f"Saved: {args.output}")


if __name__ == "__main__":
    main()
